texteexpo_index:
    path:     /
    defaults: { _controller: "ModuleGestionBundle:TexteExpo:index" }
    methods:  GET

texteexpo_show:
    path:     /{id}/show
    defaults: { _controller: "ModuleGestionBundle:TexteExpo:show" }
    methods:  GET

texteexpo_new:
    path:     /new
    defaults: { _controller: "ModuleGestionBundle:TexteExpo:new" }
    methods:  [GET, POST]

texteexpo_edit:
    path:     /{id}/edit
    defaults: { _controller: "ModuleGestionBundle:TexteExpo:edit" }
    methods:  [GET, POST]

texteexpo_delete:
    path:     /{id}/delete
    defaults: { _controller: "ModuleGestionBundle:TexteExpo:delete" }
    methods:  DELETE
