traductionexpo_index:
    path:     /
    defaults: { _controller: "ModuleGestionBundle:TraductionExpo:index" }
    methods:  GET

traductionexpo_show:
    path:     /{id}/show
    defaults: { _controller: "ModuleGestionBundle:TraductionExpo:show" }
    methods:  GET

traductionexpo_new:
    path:     /new
    defaults: { _controller: "ModuleGestionBundle:TraductionExpo:new" }
    methods:  [GET, POST]

traductionexpo_edit:
    path:     /{id}/edit
    defaults: { _controller: "ModuleGestionBundle:TraductionExpo:edit" }
    methods:  [GET, POST]

traductionexpo_delete:
    path:     /{id}/delete
    defaults: { _controller: "ModuleGestionBundle:TraductionExpo:delete" }
    methods:  DELETE
