# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.form.registration:
        class: ModuleGestionBundle\Form\UtilisateurType
        tags:
            - { name: form.type, alias: app_user_registration }
            
    # modulegestion.password_resetting:
    #     class: ModuleGestionBundle\EventListener\PasswordResettingListener
    #     arguments: [ '@router' ]
    #     tags:
    #         - { name: 'kernel.event_subscriber' }
