module_gestion_homepage:
    path:     /
    defaults: { _controller: FOSUserBundle:Security:login }

module_gestion_index:
    path:     /accueil
    defaults: { _controller: ModuleGestionBundle:Security:login }

statistique_expo:
    path:     /statistique_expo
    defaults: { _controller: ModuleGestionBundle:Statistique:chartexpo }

statistique_oeuvre:
    path:     /statistique_oeuvre
    defaults: { _controller: ModuleGestionBundle:Statistique:chartoeuvre }

module_gestion_exposition:
    resource: "@ModuleGestionBundle/Resources/config/routing/exposition.yml"
    prefix:   /exposition

module_gestion_oeuvre:
    resource: "@ModuleGestionBundle/Resources/config/routing/oeuvre.yml"
    prefix:   /oeuvre

module_gestion_artiste:
    resource: "@ModuleGestionBundle/Resources/config/routing/artiste.yml"
    prefix:    /artiste

list_oeuvre:
    path:    /list/oeuvre
    defaults: { _controller: "ModuleGestionBundle:Oeuvre:listOeuvre" }
    methods: [POST]

test_unit_oeuvre:
    path:    /test_unit/oeuvre
    defaults: { _controller: "ModuleGestionBundle:Oeuvre:testUnite" }
    methods: [POST]

test_scan_oeuvre:
    path:   /scan
    defaults: { _controller: "ModuleGestionBundle:Scan:TestScan" }
    methods: [GET]

test_oeuvre:
    path:    /testoeuvre/{id}/show
    defaults: { _controller: "ModuleGestionBundle:Oeuvre:testOeuvre" }
    methods: [GET]

module_gestion_utilisateur:
    resource: "@ModuleGestionBundle/Resources/config/routing/utilisateur.yml"
    prefix:    /utilisateur

module_gestion_organisateur:
    resource: "@ModuleGestionBundle/Resources/config/routing/organisateur.yml"
    prefix:    /organisateur

module_gestion_auteur:
    resource: "@ModuleGestionBundle/Resources/config/routing/auteur.yml"
    prefix:   /auteur

module_gestion_collectif:
    resource: "@ModuleGestionBundle/Resources/config/routing/collectif.yml"
    prefix:   /collectif

EndroidQrCodeBundle:
    resource:   "@EndroidQrCodeBundle/Controller/"
    type:       annotation
    prefix:     /qrcode

module_gestion_theme:
    resource: "@ModuleGestionBundle/Resources/config/routing/theme.yml"
    prefix:   /theme
