module_gestion_homepage:
    path:     /
    defaults: { _controller: FOSUserBundle:Security:login }

module_gestion_index:
    path:     /accueil
    defaults: { _controller: ModuleGestionBundle:Default:index }