module_gestion_homepage:
    path:     /
    defaults: { _controller: FOSUserBundle:Security:login }

module_gestion_index:
    path:     /accueil
    defaults: { _controller: ModuleGestionBundle:Security:login }

module_gestion_exposition:
    resource: "@ModuleGestionBundle/Resources/config/routing/exposition.yml"
    prefix:   /exposition

module_gestion_utilisateur:
    resource: "@ModuleGestionBundle/Resources/config/routing/utilisateur.yml"
    prefix:    /utilisateur