module_gestion_homepage:
    path:     /
    defaults: { _controller: FOSUserBundle:Security:login }

module_gestion_index:
    path:     /accueil
    defaults: { _controller: ModuleGestionBundle:Security:login }

module_gestion_exposition:
    resource: "@ModuleGestionBundle/Resources/config/routing/exposition.yml"
    prefix:   /exposition

module_gestion_utilisateur:
    resource: "@ModuleGestionBundle/Resources/config/routing/utilisateur.yml"
    prefix:    /utilisateur

module_gestion_texteexpo:
    resource: "@ModuleGestionBundle/Resources/config/routing/texteexpo.yml"
    prefix:   /texteexpo

module_gestion_traductionexpo:
    resource: "@ModuleGestionBundle/Resources/config/routing/traductionexpo.yml"
    prefix:   /traductionexpo

module_gestion_langue:
    resource: "@ModuleGestionBundle/Resources/config/routing/langue.yml"
    prefix:   /langue