ModuleGestionBundle\Entity\Collectif:
    type: entity
    table: null
    repositoryClass: ModuleGestionBundle\Repository\CollectifRepository
    fields:
        datecreation:
            type: datetime
    lifecycleCallbacks: {  }
