ModuleGestionBundle\Entity\Emplacement:
    type: entity
    table: null
    repositoryClass: ModuleGestionBundle\Repository\EmplacementRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        position:
            type: integer
    manyToOne:
        exposition:
            targetEntity: ModuleGestionBundle\Entity\Exposition
            joinColumn:
                nullable: false
    manyToOne:
        oeuvre:
            targetEntity: ModuleGestionBundle\Entity\Oeuvre
            joinColumn:
                nullable: false

    lifecycleCallbacks: {  }
