ModuleGestionBundle\Entity\Emplacement:
    type: entity
    table: null
    repositoryClass: ModuleGestionBundle\Repository\EmplacementRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        position:
            type: integer
    manyToOne:
        exposition:
            targetEntity: Exposition
            inversedBy: emplacements
            joinColumn:
                name: exposition_id
                referencedColumnName: id
                nullable: false
    manyToOne:
        oeuvre:
            targetEntity: Oeuvre
            inversedBy: emplacements
            joinColumn:
                name: oeuvre_id
                referencedColumnName: id
                nullable: false

    lifecycleCallbacks: {  }
