ModuleGestionBundle\Entity\Langue:
    type: entity
    table: null
    repositoryClass: ModuleGestionBundle\Repository\LangueRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nomLangue:
            type: string
            length: 255
            column: NomLangue
    lifecycleCallbacks: {  }
