ModuleGestionBundle\Entity\TexteOeuvre:
    type: entity
    table: null
    repositoryClass: ModuleGestionBundle\Repository\TexteOeuvreRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        description:
            type: text
    manyToOne:
        oeuvre:
            targetEntity: Oeuvre
            inversedBy: texteoeuvres
            joinColumn:
                name: oeuvre_id
                referencedColumnName: id

    lifecycleCallbacks: {  }
