ModuleGestionBundle\Entity\TextExposition:
    type: entity
    table: null
    repositoryClass: ModuleGestionBundle\Repository\TextExpositionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        description:
            type: string
            length: 255
        langue:
            type: string
            length: 255

    manyToOne:
        exposition:
            targetEntity: ModuleGestionBundle\Entity\Exposition
            inversedBy: telephones
            joinColumn:
                name: exposition_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
