ModuleGestionBundle\Entity\TexteExpo:
    type: entity
    table: null
    repositoryClass: ModuleGestionBundle\Repository\TexteExpoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        descriptionTextexpo:
            type: string
            length: 255
            column: description_textexpo
    lifecycleCallbacks: {  }
