ModuleGestionBundle\Entity\TraductionExpo:
    type: entity
    table: null
    repositoryClass: ModuleGestionBundle\Repository\TraductionExpoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToOne:
        langue:
            targetEntity: ModuleGestionBundle\Entity\Langue
            joinColumn:
                name: langue_id
                referencedColumnName: id
    manyToOne:
        exposition:
            targetEntity: ModuleGestionBundle\Entity\Exposition
            inversedBy: traductionexpos
            cascade: ["remove"]
            joinColumn:
                name: exposition_id
                referencedColumnName: id
                
    lifecycleCallbacks: {  }
