ModuleGestionBundle\Entity\Utilisateur:
    type: entity
    table: null
    repositoryClass: ModuleGestionBundle\Repository\UtilisateurRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstname:
            type: string
            length: 255
            column: firstname
        lastname:
            type: string
            length: 255
            column: lastname
        role:
            type: string
            length: 255
            column: role
    oneToMany:
        telephones:
            targetEntity: ModuleGestionBundle\Entity\Telephone
            mappedBy: utilisateur
            cascade: ["remove","persist"] 
    
    lifecycleCallbacks: {  }