<?php

namespace ModuleGestionBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * ExpositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpositionRepository extends \Doctrine\ORM\EntityRepository
{

	public function findAllCurrent(){

		$date1 = new \Datetime();
		$date2 = new \Datetime();

		$dateDeb = date_sub($date1, date_interval_create_from_date_string('7 days')); // 2016-07-03 00:00:00
		$dateDeb = date_time_set($dateDeb, 00, 00, 00);

		$dateFin = date_sub($date2, date_interval_create_from_date_string('7 days')); // 2016-07-03 23:59:59
		$dateFin = date_time_set($dateFin, 23, 59, 59);

		$parameters = array(
			'deliver' => 'Livré',
			'dateSearchDeb' => $date1,
			'dateSearchFin' => $date2
				);

		$query = $this->_em->createQuery('
			SELECT ex, o, e
			FROM ModuleGestionBundle:Exposition ex
			INNER JOIN ex.emplacements e
			INNER JOIN e.oeuvre o
			WHERE o.etat != :deliver
			AND ex.dateHeureDebutExposition
			BETWEEN :dateSearchDeb AND :dateSearchFin'
			)->setParameters($parameters);

		return $query->getResult();
	}

}
