<?php

namespace ModuleGestionBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * ExpositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpositionRepository extends \Doctrine\ORM\EntityRepository
{

	public function findAllCurrent(){

		// Date de début 7 jours après la date du jour initialisée à 00:00:00
		$dateDeb = new \Datetime();
		$dateDeb = date_add($dateDeb, date_interval_create_from_date_string('7 days'));
		$dateDeb = date_time_set($dateDeb, 00, 00, 00);

		// Date de fin 7 jours après la date du jour initialisée à 23:59:59
		$dateFin = new \Datetime();
		$dateFin = date_add($dateFin, date_interval_create_from_date_string('7 days'));
		$dateFin = date_time_set($dateFin, 23, 59, 59);

		$parameters = array(
			'deliver' => 'Livré',
			'dateSearchDeb' => $dateDeb,
			'dateSearchFin' => $dateFin
				);

		$query = $this->_em->createQuery('
			SELECT ex, o, e
			FROM ModuleGestionBundle:Exposition ex
			INNER JOIN ex.emplacements e
			INNER JOIN e.oeuvre o
			WHERE o.etat != :deliver
			AND ex.dateHeureDebutExposition
			BETWEEN :dateSearchDeb AND :dateSearchFin' 
			)->setParameters($parameters);

		return $query->getResult();
	}

}
