<?php

namespace ModuleGestionBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * OeuvreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OeuvreRepository extends \Doctrine\ORM\EntityRepository
{
	public function getFindAllOeuv(){

		$query = $this->_em->createQuery('
			SELECT o, e, a, t
			FROM ModuleGestionBundle:Oeuvre o
			LEFT JOIN o.emplacements e
			INNER JOIN o.artiste a
			LEFT JOIN o.typeoeuvre t');

		return $query->getResult();

	}
}
