<?php

namespace ModuleGestionBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * OeuvreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OeuvreRepository extends \Doctrine\ORM\EntityRepository
{
	// public function getFindAllOeuv(){

	// 	$query = $this->_em->createQuery('SELECT o.nom,o.etat,a.nom as nomArt,a.prenom as preNomArt,o.nombreVisite,e.position,o.id,o.imgFlashcode as img, t.discr as type 
	// 			FROM ModuleGestionBundle:Oeuvre o 
	// 			LEFT JOIN ModuleGestionBundle:Emplacement e 
	// 				ON e.oeuvre_id = o.id
	// 			INNER JOIN ModuleGestionBundle:Artiste a 
	// 				ON o.artiste_id = a.id
	// 			LEFT JOIN ModuleGestionBundle:TypeOeuvre t
	// 				ON o.typeoeuvre = t.id');

	// 	$results = $query->getResult();

	// 	return $results;

	// }
}
