<?php

namespace ModuleGestionBundle\Repository;

/**
 * TexteExpoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TexteExpoRepository extends \Doctrine\ORM\EntityRepository
{
}
