<?php

namespace ModuleGestionBundle\Repository;

/**
 * TraductionExpoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TraductionExpoRepository extends \Doctrine\ORM\EntityRepository
{
}
