module_diffusion_homepage:
    path:     /
    defaults: { _controller: ModuleDiffusionBundle:Accueil:index }

affiche_calendar:
    path:    /calendrier
    defaults: { _controller: "ModuleDiffusionBundle:Default:affiche" }
    methods: [POST, GET]